name: C++ CI

on: [push, pull_request]

jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
      - name: Install Dependencies for Linux
        run: |
          mkdir -p interactive_engine/distribution/target/
          touch interactive_engine/distribution/target/maxgraph.tar.gz
      - name: Upload tools for helm test to Artifact
        uses: actions/upload-artifact@v2
        with:
          name: maxgraph.tar.gz
          path: interactive_engine/distribution/target/maxgraph.tar.gz
          retention-days: 5

  download:
    needs: [upload]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v2
        with:
          name: maxgraph.tar.gz
          path: artifacts
      - name: ls
        run: |
          ls artifacts
          echo "----------"
          ls artifacts/*
          echo "----------"
          ls .
