name: GraphScope CI

on: [push, pull_request]

jobs:
  build_analytical:
    runs-on: ubuntu:latest
    steps:
    - name: Build Image
      run:
        mkdir ${{ github.workspace }}/install
        touch install/a
        mkdir -p install/b/c

    - name: Upload Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: analytical-${{ github.sha }}
        path: ${{ github.workspace }}/install
        retention-days: 5

    - name: Download Artifacts
      uses: actions/download-artifact@v3
      with:
        name: analytical-${{ github.sha }}
        path: ${{ github.workspace }}/artifacts/analytical/install
    - name: LS
      run:
        tree ./artifacts

